name: Desafio Um Giropos COntainer

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: "Nome da imagem pública do Docker Hub (ex: alpine, nginx, ubuntu)"
        required: true
        default: "alpine"
        type: string

jobs:
  scan-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Pull Docker image
        run: docker pull ${{ github.event.inputs.image_name }}

      - name: List Docker image
        run: |
          IMAGE_NAME=$(echo "${{ github.event.inputs.image_name }}" | cut -d ':' -f 1) 
          docker images | grep $IMAGE_NAME

      - name: Scan vulnerabilities with Docker Scout
        uses: docker/scout-action@v1
        with:
          image: ${{ github.event.inputs.image_name }}
          only-severities: critical, high
        #run: |
         # curl -fsSL https://get.docker.com/rootless | sh
          #docker scout cves $IMAGE_NAME
