name: Docker Image Security Scan

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: "Nome da imagem pública do Docker Hub (ex: alpine, nginx, ubuntu)"
        required: true
        default: "alpine"
        type: string

jobs:
  scan-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Login do docker HUB
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Pull Docker image
        run: docker pull ${{ github.event.inputs.image_name }}

      - name: List Docker image
        run: |
          IMAGE_NAME=$(echo "${{ github.event.inputs.image_name }}" | cut -d ':' -f 1) 
          docker images | grep $IMAGE_NAME

      - name: Scan vulnerabilities with Docker Scout
        uses: docker/scout-action@v1
        with:
          command: quickview,cves,recommendations,sbom
          image: ${{ github.event.inputs.image_name }}
          only-severities: critical, high
        #run: |
         # curl -fsSL https://get.docker.com/rootless | sh
          #docker scout cves $IMAGE_NAME
